### ISSUE TITLE
DeprecationWarning: django.utils.simplejson is deprecated; use json instead.

### ISSUE THREAD

**Issue by rajsubit** [arthurk/django-disqus#43]
Simple json is depreciated beyond django 1.5 and is recommended to use json.

**Comment by kanhaiyakumawat** [comment]
This issue still seems to be there.. any alternative of the django-disqus?

**Comment by arthurk** [comment]
If any of you wants to maintain this project i'd be more than happy

**Comment by kanhaiyakumawat** [comment]
@arthurk thanks much for upgrading it with django 1.7 support. It is working like charm. I am new in django, hence little hesitant to own full maintenance of this project, but I am ready to take it slow. Let me know if I can help somehow!!

**Comment by arthurk** [comment]
@kanhaiyakumawat ok!

i'm closing this issue since it has been fixed.
